"""Deterministic application-readiness evaluation (document-checklist spec).

Pure function: readiness is computed from official document requirements and the
citizen's selections, never generated by a model (ai-rag.md).
"""

from __future__ import annotations

from .models import (
    DocumentKind,
    Readiness,
    ReadinessResult,
    ServiceRecord,
    VerificationStatus,
)


def evaluate_readiness(
    service: ServiceRecord,
    held: set[str],
    condition_answers: dict[str, bool],
) -> ReadinessResult:
    """Compute READY / NOT_READY / NEEDS_VERIFICATION for a service.

    - held: document ids the citizen marked as available.
    - condition_answers: for conditional docs, whether the condition applies.
      Missing answer for a conditional doc => unknown => NEEDS_VERIFICATION.
    """
    reasons: list[str] = []
    missing_required = []
    applicable_conditional_missing = []
    needs_verification = False

    # Unverified service can never be READY.
    if service.status == VerificationStatus.UNVERIFIED:
        needs_verification = True
        reasons.append("Service record is unverified.")

    if not service.documents:
        reasons.append("No document information available in the knowledge base.")
        return ReadinessResult(
            status=Readiness.NEEDS_VERIFICATION,
            reasons=reasons,
        )

    for doc in service.documents:
        if doc.kind == DocumentKind.OPTIONAL:
            continue

        # A required doc without a backing source triggers verification.
        if doc.kind == DocumentKind.REQUIRED and not doc.source_ref:
            needs_verification = True
            reasons.append(f"Required document '{doc.id}' lacks a source reference.")

        if doc.kind == DocumentKind.REQUIRED:
            if doc.id not in held:
                missing_required.append(doc)
            continue

        # Conditional documents
        if doc.kind == DocumentKind.CONDITIONAL:
            if doc.id not in condition_answers:
                needs_verification = True
                reasons.append(
                    f"Cannot determine if conditional document '{doc.id}' applies."
                )
                continue
            applies = condition_answers[doc.id]
            if applies and doc.id not in held:
                applicable_conditional_missing.append(doc)

    if missing_required or applicable_conditional_missing:
        return ReadinessResult(
            status=Readiness.NOT_READY,
            missing_required=missing_required,
            applicable_conditional_missing=applicable_conditional_missing,
            reasons=reasons or ["One or more required documents are missing."],
        )

    if needs_verification:
        return ReadinessResult(
            status=Readiness.NEEDS_VERIFICATION,
            reasons=reasons,
        )

    return ReadinessResult(status=Readiness.READY, reasons=["All required documents are available."])
